# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-30 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
