# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-04 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Company ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='Company Name')),
                ('c_email', models.CharField(max_length=30, verbose_name='Company E-mail')),
                ('c_address', models.TextField(verbose_name='Company Address')),
                ('c_phone', models.CharField(max_length=20, verbose_name='Company Phone')),
                ('c_password', models.CharField(max_length=6, verbose_name='Company Password')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('d_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Department ID')),
                ('d_name', models.CharField(max_length=30, verbose_name='Department Name')),
                ('d_capacity', models.IntegerField(verbose_name='Department Capacity')),
                ('d_phone', models.IntegerField(verbose_name='Department Phone')),
                ('d_password', models.CharField(max_length=6, verbose_name='Department Password')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Employee ID')),
                ('e_name', models.CharField(max_length=30, verbose_name='Name')),
                ('e_surname', models.CharField(max_length=30, verbose_name='Surname')),
                ('e_password', models.CharField(max_length=6, verbose_name='Password')),
                ('e_email', models.CharField(max_length=30, verbose_name='Email')),
                ('e_phone', models.IntegerField(verbose_name='Phone')),
                ('e_degree', models.IntegerField(verbose_name='Degree')),
                ('e_salary', models.IntegerField(verbose_name='Salary')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Project ID')),
                ('p_startdate', models.DateTimeField(verbose_name='Project Start Date')),
                ('p_enddate', models.DateTimeField(verbose_name='Project End Date')),
                ('p_title', models.CharField(max_length=75, verbose_name='Project Title')),
                ('p_situation', models.CharField(max_length=20, verbose_name='Project Situation')),
                ('dProject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='Department ID')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.Company')),
                ('f_rating', models.IntegerField(verbose_name='Foreign Company Rating')),
            ],
            bases=('company.company',),
        ),
        migrations.AddField(
            model_name='employee',
            name='eCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='eDepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Department', verbose_name='Department ID'),
        ),
        migrations.AddField(
            model_name='department',
            name='dCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company id'),
        ),
    ]
