# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['e_degree']},
        ),
        migrations.AddField(
            model_name='employee',
            name='eImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='d_slug',
            field=models.SlugField(unique=True),
        ),
    ]
