# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-01 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_price', models.IntegerField(verbose_name='Project Price')),
                ('h_type', models.CharField(max_length=50, verbose_name='Help Type')),
                ('h_timestart', models.DateTimeField(verbose_name='Help Time Start')),
                ('h_timeend', models.DateTimeField(verbose_name='Help Time End')),
                ('cHelps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Which Company Helps (ID)')),
                ('pHelps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Project', verbose_name='Which Project Helps (ID)')),
            ],
        ),
    ]
