# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-04 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('eHead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.Employee', unique=True, verbose_name='Employee')),
                ('h_degree', models.IntegerField(verbose_name='Head Degree')),
            ],
        ),
        migrations.CreateModel(
            name='Helps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_price', models.IntegerField(verbose_name='Project Price')),
                ('h_type', models.CharField(max_length=50, verbose_name='Help Type')),
                ('h_timestart', models.DateTimeField(verbose_name='Help Time Start')),
                ('h_timeend', models.DateTimeField(verbose_name='Help Time End')),
                ('cHelps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Which Company Helps (ID)')),
                ('pHelps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Project', verbose_name='Which Project Helps (ID)')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Issue ID')),
                ('i_type', models.CharField(max_length=30, verbose_name='Issue Type')),
                ('i_extra', models.TextField(verbose_name='Issue Notes')),
                ('i_content', models.TextField(verbose_name='Issue Content')),
                ('pIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Project', verbose_name='Project ID')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('eOther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.Employee', unique=True, verbose_name='Employee')),
                ('o_studyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Project', verbose_name='Works Project ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectPlan',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Plan ID')),
                ('plan_type', models.CharField(max_length=30, verbose_name='Plan Type')),
                ('plan_date', models.DateTimeField(verbose_name='Plan Date')),
                ('headMakes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Head', verbose_name='Head ID')),
                ('pProjectPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Project', verbose_name='Project ID')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_type', models.CharField(max_length=30, verbose_name='Report Type')),
                ('r_version', models.CharField(max_length=5, verbose_name='Report Version')),
                ('r_createdate', models.DateTimeField(verbose_name='Report Create Date')),
                ('oReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Other', verbose_name='Prepare Employee ID')),
                ('pReport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Project', verbose_name='Project ID')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('sub_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Subtask ID')),
                ('iIssue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Issue', verbose_name='Issue ID')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_type', models.CharField(max_length=30, verbose_name='Workflow Type')),
                ('w_date', models.DateTimeField(verbose_name='Workflow Date')),
            ],
        ),
    ]
