# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-30 03:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Head',
            fields=[
                ('eHead', models.ForeignKey(auto_created=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.Employee', verbose_name='Employee')),
                ('h_degree', models.IntegerField(verbose_name='Head Degree')),
            ],
        ),
    ]
