# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-01 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('eOther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='company.Employee', unique=True, verbose_name='Employee')),
                ('o_studyproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Project', verbose_name='Works Project ID')),
            ],
        ),
    ]
