# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_helps'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignCompany',
            fields=[
                ('company_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.Company')),
                ('f_rating', models.IntegerField(verbose_name='Foreign Company Rating')),
            ],
            bases=('company.company',),
        ),
    ]
