# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190105_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eImage',
            new_name='Image',
        ),
    ]
