# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190105_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='eProject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Employee', verbose_name='Project Manager'),
            preserve_default=False,
        ),
    ]
