# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20181230_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('c_id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('c_name', models.CharField(max_length=30, verbose_name='Company Name')),
                ('c_email', models.CharField(max_length=30, verbose_name='Company E-mail')),
                ('c_address', models.TextField(verbose_name='Company Address')),
                ('c_password', models.CharField(max_length=6, verbose_name='Company Password')),
            ],
        ),
    ]
