# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_project_eproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProjectS', to='company.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='eProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='company.Employee'),
        ),
    ]
