# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20190105_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='eProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name', to='company.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surname', to='company.Employee'),
        ),
    ]
