# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20190105_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sProject', to='company.Employee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='eProject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eProject', to='company.Employee', verbose_name='Project Manager'),
        ),
    ]
