# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_auto_20190105_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cProject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Company Name'),
            preserve_default=False,
        ),
    ]
