# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-05 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_project_cproject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterField(
            model_name='department',
            name='d_slug',
            field=models.SlugField(editable=False, max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='e_slug',
            field=models.SlugField(editable=False, max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='p_slug',
            field=models.SlugField(editable=False, max_length=130, unique=True),
        ),
    ]
